set -g mode-keys vi

set-option -g mouse on

set-option -g default-command "reattach-to-user-namespace -l zsh"
# Change the default prefix
unbind-key C-b
set -g prefix C-a

# Prefix a
bind-key a send-prefix

# Prefix ctrl-a
bind-key C-a last-window

# Repeat time limit (ms)
set-option -g repeat-time 400

# Prefix c
bind-key c new-window -c "#{pane_current_path}"

# Prefix
bind-key -r '-' split-window -v -c "#{pane_current_path}"
bind-key -r '|' split-window -h -c "#{pane_current_path}"

# Moving windows
bind-key -r > swap-window -t :+
bind-key -r < swap-window -t :-

# Tile panes
bind-key t select-layout tiled

# Don't wair for escape keys
set -s escape-time 0

# Enable focus events
set -g focus-events on

# Pane-movement
bind-key -r h select-pane -L
bind-key -r l select-pane -R
bind-key -r j select-pane -D
bind-key -r k select-pane -U

# Pane resizing
unbind L
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -r n next-window
bind -r p previous-window

bind -r ( switch-client -p
bind -r ) switch-client -n

# Synchronize panes
bind-key * set-window-option synchronize-pane

# Reload ~/.tmux.conf
bind-key R source-file ~/.tmux.conf \; display-message "Reloaded!"

# Set colors
set -g default-terminal "screen-256color"

bind-key & kill-window
bind-key x kill-pane

# Renumber windows when a window is closed
set-option -g renumber-windows on

source ~/.tmux_airline

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'nhdaly/tmux-scroll-copy-mode'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'

# for neovim
set -g @resurrect-capture-pane-contents 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
