set -g mode-keys emacs

set-option -g mouse on

# set-option -g default-command "reattach-to-user-namespace -l zsh"
if-shell "uname | grep -q Darwin" "set-option -g default-command \"reattach-to-user-namespace -l zsh\""
unbind-key C-b
unbind-key C-a
unbind-key %
unbind-key '"'
unbind-key &

# Change the default prefix
set -g prefix C-a

set-option -g allow-rename off

# Prefix a
bind-key a send-prefix

# Prefix ctrl-a
bind-key C-a last-window

# Repeat time limit (ms)
set-option -g repeat-time 400

# Prefix c
bind-key c new-window -c "#{pane_current_path}"

# Prefix
bind-key -r '-' split-window -v -c "#{pane_current_path}"
bind-key -r '|' split-window -h -c "#{pane_current_path}"

bind-key X kill-window
bind-key x kill-pane
bind-key q confirm-before kill-session
bind-key Q confirm-before kill-server

# Moving windows
bind-key -r > swap-window -t :+
bind-key -r < swap-window -t :-

# Tile panes
bind-key t select-layout tiled

# Don't wair for escape keys
set -s escape-time 0

# Enable focus events
set -g focus-events on

# Pane-movement
bind-key -r c-h select-pane -L
bind-key -r c-l select-pane -R
bind-key -r c-j select-pane -D
bind-key -r c-k select-pane -U

bind -r c-n next-window
bind -r c-p previous-window

# Synchronize panes
bind-key * set-window-option synchronize-pane

# Reload ~/.tmux.conf
bind-key R source-file ~/.tmux.conf \; display-message "Reloaded!"

# Set colors
set -g default-terminal "screen-256color"

# Renumber windows when a window is closed
set-option -g renumber-windows on

source ~/.tmux_airline

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'nhdaly/tmux-scroll-copy-mode'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
