export DISABLE_AUTO_TITLE=true
export EDITOR='/usr/local/bin/nvim'
export LESS='-g -i -M -R -S -w -X -z-4'
export VISUAL='/usr/local/bin/nvim'

# ZSH options
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt NO_INC_APPEND_HISTORY     # Write to the history file only when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.
setopt HISTIGNORESPACE           # Don't save commands with leading space to history
setopt NO_CORRECT                # Turn off autocorrect

# Z settings
Z_SCRIPT="$HOME/.config/z/z.sh"
[[ -s $Z_SCRIPT ]] && source $Z_SCRIPT

# FZF settings
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.fzf-key-bindings.zsh ] && source ~/.fzf-key-bindings.zsh
[ -f ~/.fzf-funcs.zsh ] && source ~/.fzf-funcs.zsh
[ -f ~/.shortcuts.zsh ] && source ~/.shortcuts.zsh

export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_DEFAULT_OPTS='--color=dark,bg+:18 --bind=ctrl-z:toggle-up --inline-info --height 50% --no-reverse --border'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS='--no-reverse'

# Pyenv settings
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/scripts/base16-eighties.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# Add ~/bin directory to my path
if [ -d "$HOME/bin" ] ; then
    PATH="$PATH:$HOME/bin"
fi

PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

# virtualenv-wrapper
export WORKON_HOME=~/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
VIRTUALENVWRAPPER="/usr/local/bin/virtualenvwrapper.sh"
[[ -s $VIRTUALENVWRAPPER ]] && source $VIRTUALENVWRAPPER

[[ $TMUX = "" ]] && export TERM="xterm-256color" || TERM="screen-256color"

[[ -s $HOME/.zshrc.local ]] && source $HOME/.zshrc.local

[[ -s $HOME/.config/k ]] && source $HOME/.config/k/k.sh

# Prepent path for brew installed packages
PATH="/usr/local/bin:$PATH"

# Edit long commands with vim
autoload edit-command-line
zle -N edit-command-line
bindkey '^g^g' edit-command-line
